# Reload config with Prefix + r
unbind r
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Set prefix to Ctrl-a
set -g prefix C-a

# Enable mouse support
set -g mouse on

# Use vi mode for copy mode
setw -g mode-keys vi

# Pane navigation with h, j, k, l
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Move status bar to top
set-option -g status-position top

# Tmux Plugin Manager (TPM) and plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#2.1.3'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'alexanderjeurissen/tmux-world-clock'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'omerxx/tmux-floax'

# Catppuccin theme settings
set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha
set -g @catppuccin_window_status_style "rounded"

# Status bar configuration
set -g status-left "#{E:@catppuccin_status_application}"
set -g status-left-length 100

# Right side: Time as a Catppuccin component + Battery + World Clock
set -gF status-right "#{E:@catppuccin_status_right_separator}#[fg=#cdd6f4,bg=#1e1e2e,bold] %H:%M #[fg=#1e1e2e]#{E:@catppuccin_status_right_separator}#[default]#{E:@catppuccin_status_battery}"
set-option -agF status-right " #[bg=blue,fg=black]#{world_clock_status}"
set -g status-right-length 100

# Set default shell
set-option -g default-shell /run/current-system/sw/bin/zsh

# Initialize TPM (must be at the bottom)
run '~/.tmux/plugins/tpm/tpm'
